name: ${project.name}
author: gronnmann
description: ${project.description}
version: ${project.version}
main: io.github.gronnmann.chatperworld.Main
softdepend: [PlaceholderAPI]

commands:
    chatperworld:
        description: Main plugin command.
        aliases: [cpw]